### ISSUE TITLE
Order of Current/Past Board Members

### ISSUE THREAD

**Issue by KatherineMichel** [DEFNA/old.defna.org#17]
Determine an approach for order of board members (first/last name, tenure, role, etc.)

**Comment by logankilpatrick** [comment]
I would vote last name or first name just to keep it simple

**Comment by jefftriplett** [comment]
Jekyll likes to sort collections by filename, but we have an `order` field in our frontmatter files which means we are probably sorting by it. I don't have a preference, but we have some options if something doesn't look right.

**Comment by jefftriplett** [comment]
closing because we have two ways of sorting now.
